-- Create doctors table for Oracle
CREATE TABLE DOCTORS (
  DOCTOR_ID       NUMBER NOT NULL PRIMARY KEY,
  ALLOWED_FEATURES CLOB,
  DOCTOR_TYPE     VARCHAR2(20) DEFAULT 'طبيب عام' CHECK (DOCTOR_TYPE IN ('أخصائي','طبيب عام')),
  IS_ACTIVE       NUMBER(1) DEFAULT 1,
  CREATED_AT      TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP,
  UPDATED_AT      TIMESTAMP WITH TIME ZONE
);

-- Optional JSON check if Oracle version supports it
BEGIN
  EXECUTE IMMEDIATE 'ALTER TABLE DOCTORS ADD CONSTRAINT CHK_ALLOWED_FEATURES_JSON CHECK (ALLOWED_FEATURES IS JSON)';
EXCEPTION
  WHEN OTHERS THEN
    NULL; -- ignore if not supported
END;
